### ISSUE TITLE
안녕하세요 Dto 예제 사용과 관련하여 여쭤보고 싶은게 있습니다

### ISSUE THREAD

**Issue by ktj1312** [cheese10yun/spring-jpa-best-practices#22]
안녕하세요
좋은 예제 올려주신점에 감사합니다.
예제를 보고 연습을 하던 중 궁금한 사항이 있어 질문을 드리고자합니다..(따로 질문 칸이 없어 이슈에 올리게 되었습니다.)
 저는 스프링 부트 사용중입니다. 
https://spring.io/guides/gs/handling-form-submission/
위 예제를 보셨을 때 다름이 아니고 웹에서 MVC컨트롤러로 값을 받아오는 중 form 처리에 있어 ModelAttribute로 받음에 있어 setter로 해당 파라미터들이 들어가게 되는 것 같습니다.
 하지만 Dto 상에 Setter가 없기 때문에 해당 파라미터들이 정상적으로 set이 되지 않아 null로 표시되고 있습는 것 같습니다.
 혹 이런 시점에 적절한 방법이 있을까요?

 감사합니다.

**Comment by cheese10yun** [comment]
```java
@PostMapping("/greeting")
@ResponseBody
public Greeting greetingSubmit(@RequestBody Greeting greeting) {
    return greeting;
}
public class Greeting {
    private long id;
    private String content;

    protected Greeting() {
    }
    public long getId() {
        return id;
    }
    public String getContent() {
        return content;
    }
}
```

네 안녕하세요. 우선 이슈 남겨 주셔서 감사합니다.

@ktj1312 님이 물어보신 제가 @ModelAttribute 사용경험이 없어 setter 없이 바인딩시키는 방법은 저도 잘 모르겠네요. 

예제코드를 직접 돌려봤는데요. Greeting value class에 query parameter 방식으로 바인딩 되더라고요.


**해당 데이터를 보낼 때는 body 값으로 보내는 것이 바람직하다고 생각합니다.** body 값 기반으로 Greeting 바인딩 될 때는 자바 리플랙션이 일어나기 때문에 반드시 NoArgsConstructor 생성자를 구현하셔야 합니다. 또 protected를 두는 것이 외부 객체에서 생성을 최소화 할 수 있으므로 조금 더 바람직하다고 생각합니다.

**굳이 query parameter 방식을 사용할 이유가 없다면 위의 예제 코드처럼 @RequestBody을 통해서 받으시는 것 적극 추천해 드립니다.**

**Comment by cheese10yun** [comment]
@ktj1312 
혹시 query parameter  방식으로 받아야하는 명확한 이유가 있을까요?

**Comment by ktj1312** [comment]
@cheese10yun 답변 달아주셔서 감사합니다.
사실 일반적인 사용에서는 전혀 문제가 없었습니다만
받는 객체에 파일을 추가하면서 해당 방식에 문제가 있었어서 질문을 드리게 되었습니다.
아래와 같이 Dto 구성을 하였을 때 form-data로 전송을 하기 때문인지 ReqestBody를 이용해 인자를 
받을 수 없었습니다.
그래서 `@modelAttribute`를 이용하였었습니다.

```
	@Getter
	@NoArgsConstructor
	public static class SingUpReq {
		
		@NotEmpty
		private String modelName;

		@NotEmpty
		private String modelDesc;
		
		@JsonIgnore
		private MultipartFile modelImage;
		
		@Builder
		public SingUpReq(String modelName, String modelDesc, MultipartFile modelImage) {
			this.modelName = modelName;
			this.modelDesc = modelDesc;
			this.modelImage = modelImage;
		}
       }
```

감사합니다

**Comment by cheese10yun** [comment]
@ktj1312 
https://jojoldu.tistory.com/407 쿼리 파람 settet 없이 설정 하는 링크 입니다.
기존 DataBinder를 jackson 기반으로 변경하면 되네요
